# Generated by Django 4.1.7 on 2023-03-10 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('user_bio', models.TextField(default='Hello CSMedia!', max_length=350)),
                ('email_address', models.EmailField(blank=True, max_length=200)),
                ('user_avatar', models.ImageField(default='csmedia_avatar.png', upload_to='avatars/')),
                ('url_slug', models.SlugField(blank=True, unique=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('csmedia_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_friends', models.ManyToManyField(blank=True, related_name='Friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CSMediaRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_request_status', models.CharField(choices=[('send', 'Send'), ('accepted', 'Accepted')], max_length=10)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('friend_request_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='CSMediaProfiles.csmediaprofile')),
                ('friend_request_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='CSMediaProfiles.csmediaprofile')),
            ],
        ),
    ]
