# Generated by Django 4.1.7 on 2023-03-11 18:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CSMediaProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='csmediarelationship',
            managers=[
                ('relationship_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='csmediarelationship',
            name='friend_request_status',
            field=models.CharField(choices=[('Send', 'Send'), ('Accepted', 'Accepted')], max_length=10),
        ),
    ]
