# Generated by Django 4.1.7 on 2023-03-11 18:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CSMediaProfiles', '0002_alter_csmediarelationship_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='csmediarelationship',
            managers=[
                ('relationship_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
