# Generated by Django 4.1.7 on 2023-03-12 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSMediaProfiles', '0003_alter_csmediarelationship_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='csmediarelationship',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='csmediarelationship',
            name='friend_request_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='CSMediaProfiles.csmediaprofile'),
        ),
        migrations.AlterField(
            model_name='csmediarelationship',
            name='friend_request_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='CSMediaProfiles.csmediaprofile'),
        ),
    ]
