# Generated by Django 4.1.7 on 2023-03-10 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CSMediaProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField()),
                ('post_image', models.ImageField(blank=True, upload_to='CSMediaPosts', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='CSMediaProfiles.csmediaprofile')),
                ('post_likes', models.ManyToManyField(default=None, related_name='Likes', to='CSMediaProfiles.csmediaprofile')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='CSMediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=8)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('csmedia_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSMediaPosts.csmediapost')),
                ('csmedia_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSMediaProfiles.csmediaprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CSMediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(max_length=350)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('csmedia_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSMediaPosts.csmediapost')),
                ('csmedia_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSMediaProfiles.csmediaprofile')),
            ],
        ),
    ]
