# Generated by Django 4.1.7 on 2023-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSMediaProfiles', '0001_initial'),
        ('CSMediaPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmediapost',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='Likes', to='CSMediaProfiles.csmediaprofile'),
        ),
    ]
